# LAB 1.1: Środowisko Google Colab i biblioteki podstawowe

**Sztuczna Inteligencja - Informatyka, Semestr V**

**Prowadzący:** Łukasz Grala 

---

## Cele:
1. ✓ Zapoznanie z Google Colab
2. ✓ Podstawy NumPy
3. ✓ Manipulacja danymi w Pandas
4. ✓ Wizualizacja danych

---

## Część 1: Setup

In [3]:
# Importy
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Ustawienia
np.random.seed(42)
sns.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (10, 6)

print("✓ Gotowe!")
print(f"NumPy: {np.__version__}")
print(f"Pandas: {pd.__version__}")

✓ Gotowe!
NumPy: 2.3.5
Pandas: 2.3.3


### Zadanie 1.1: GPU (opcjonalne)
Runtime → Change runtime type → GPU

In [4]:
# TODO: Sprawdź GPU
import tensorflow as tf
# Twój kod:

ModuleNotFoundError: No module named 'tensorflow'

---
## Część 2: NumPy 

### Zadanie 2.1: Tworzenie tablic

In [5]:
# a) Tablica 0-9
arr_a = np.arange(10)
print(arr_a)
# b) Macierz 3x3 zer
arr_b = np.full((3,3), 0)
print(arr_b)
# c) Macierz 4x4 jedynek
arr_c = np.ones((4,4))
print(arr_c)
# d) Macierz jednostkowa 5x5
arr_d = np.eye(5)
print(arr_d)
# e) 10 liczb od 0 do 1
arr_e = np.linspace(0,1, 10)
print(arr_e)
# f) Macierz 3x3 losowa (normal)
arr_f = np.random.randint(0,10, size=(3,3))
print(arr_f)

[0 1 2 3 4 5 6 7 8 9]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[[6 3 7]
 [4 6 9]
 [2 6 7]]


### Zadanie 2.2: Operacje

In [6]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# a) a + b
result_a = a + b
print(result_a)

# # b) a * 3
# result_b = # TODO

# # c) b^2
# result_c = # TODO

# # d) suma macierzy
# result_d = # TODO

# # e) średnia wierszy
# result_e = # TODO

# # f) max kolumn
# result_f = # TODO

[11 22 33 44 55]


### Zadanie 2.3: Indeksowanie

In [ ]:
matrix = np.arange(1, 26).reshape(5, 5)
print(matrix)

# # a) Element [2, 3]
# elem = # TODO

# # b) 2. wiersz
# row = # TODO

# # c) 3. kolumna
# col = # TODO

# # d) Podmacierz 2x2 prawy dolny róg
sub = matrix[3:5, 3:5]
print(sub)
# # e) Elementy > 15
# big = # TODO

# # f) Zamień parzyste na 0
# mat_copy = matrix.copy()
# # TODO

---
## Część 3: Pandas 

### Zadanie 3.1: DataFrame

In [ ]:
# TODO: Utwórz DataFrame:
# - Imie (5 imion)
# - Wiek (20-30)
# - Miasto (5 miast)
# - Ocena (3.0-5.0)
data = {
    "name": ["Alek", "Marek", "Kacper", "Jurek", "Wiktor"],
    "age": np.random.randint(20,30, size=5),
    "city": ["Poznan", "Warszawa", "Wroclaw", "Krakow", "Gdansk"],
    "grade": np.round(np.random.uniform(3.0, 5.0, 5), 1)
}

df = pd.DataFrame(data)
print(df)

### Zadanie 3.2: Operacje podstawowe

In [ ]:
# a) head(3)
# b) info()
# c) describe()
# d) columns
# e) shape
result = df[df['age'] > 25][['name','city', 'age']]
print(result)

### Zadanie 3.3: Selekcja

In [ ]:
# a) Kolumna 'Imie'
# b) Kolumny 'Imie' i 'Wiek'
# c) Wiek > 25
# d) Poznań i Ocena > 4.0
# e) Sort by Ocena (desc)

### Zadanie 3.4: Nowe kolumny

In [ ]:
# a) Punkty = Ocena * 20
# b) Kategoria_Wieku: <25 -> Młody, else -> Dorosły
# c) Status: >=3.5 -> Zaliczony, else -> Niezaliczony
df['score'] = df['grade'] * 20

df['age_type'] = np.where(df['age'] < 25, 'mlody', 'dorosly')
df['status'] = np.where(df['grade'] >= 3.5, 'zaliczony', 'niezaliczony')
print(df)

### Zadanie 3.5: Grupowanie

In [ ]:
# a) Średni wiek po miastach
# b) Liczba osób w każdym statusie
# c) Max ocena w każdym mieście

### Zadanie 3.6: Dataset Iris

In [ ]:
from sklearn.datasets import load_iris

iris = load_iris()
iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)
iris_df['species'] = iris.target
iris_df['species'] = iris_df['species'].map({0: 'setosa', 1: 'versicolor', 2: 'virginica'})

print(iris_df.head())

In [ ]:
# a) describe()
# b) Średnia cech po gatunkach
# c) Kwiat z najdłuższym płatkiem
# d) Liczba kwiatów każdego gatunku

---
## Część 4: Wizualizacja

### Zadanie 4.1: Matplotlib

In [ ]:
# a) y = x^2 dla x od -10 do 10
x = np.linspace(-10,10, 1000)
y = x**2

plt.plot(x, y)
plt.xlabel('X')
plt.ylabel('Y')
plt.title('Parabola')
plt.grid(True)
plt.show()

In [ ]:
# b) Scatter: petal length vs width (kolor = gatunek)
from sklearn.datasets import load_iris

iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['species'] = iris.target
df['species_name'] = df['species'].map({0: 'setosa', 1: 'versicolor', 2: 'virginica'})

# b) Scatter: petal length vs width (kolor = gatunek)
plt.figure(figsize=(10, 6))

# Scatter plot dla każdego gatunku
for species_id, species_name in enumerate(['setosa', 'versicolor', 'virginica']):
    mask = df['species'] == species_id
    print(mask)
    plt.scatter(df[mask]['petal length (cm)'], 
                df[mask]['petal width (cm)'],
                label=species_name,
                alpha=0.7)

plt.xlabel('Petal Length (cm)')
plt.ylabel('Petal Width (cm)')
plt.title('Iris: Petal Length vs Petal Width by Species')
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

In [ ]:

# c) Histogram długości płatków
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['species'] = iris.target

# Histogram dla każdego gatunku
plt.figure(figsize=(10, 6))

for species_id, species_name in enumerate(['setosa', 'versicolor', 'virginica']):
    mask = df['species'] == species_id
    plt.hist(df[mask]['petal length (cm)'], 
             bins=15, 
             alpha=0.6, 
             label=species_name,
             edgecolor='black')

plt.xlabel('Petal Length (cm)')
plt.ylabel('Frequency')
plt.title('Histogram of Petal Length by Species')
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

### Zadanie 4.2: Seaborn

In [ ]:
# a) Heatmap korelacji Iris
# TODO

In [ ]:
# b) Box plot: petal length by species
# TODO

In [ ]:
# c) Pair plot Iris
# TODO

---
## Część 5: Mini-projekt Wine Quality

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv'
wine_df = pd.read_csv(url, sep=';')


In [ ]:
# TODO 2: Analiza 'quality'
# - unikalne wartości, rozkład, średnia
# - wykres słupkowy

print(wine_df['quality'].mean())

plt.figure(figsize=(8, 5))

wine_df['quality'].value_counts().sort_index().plot(kind='bar')
plt.title('Rozkład ocen jakości wina')
plt.xlabel('Jakość')
plt.ylabel('Liczba win')
plt.xticks(rotation=0)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

In [ ]:
# TODO 3: Korelacje
corr_matrix = wine_df.corr()
print(corr_matrix)

plt.figure(figsize=(10,10))
sns.heatmap(
    corr_matrix,
    annot=True,
    cmap='coolwarm',
    
)

In [ ]:
# TODO 4: Rozkłady
wine_df.hist(bins=20, figsize=(16, 12), color='coral', edgecolor='black', alpha=0.7)
plt.suptitle('Histogramy - metoda pandas', fontsize=16, y=1.00)
plt.tight_layout()


def detect_outliers_iqr(data):
   Q1 = data.quantile(0.25)
   Q3 = data.quantile(0.75)
   IQR = Q3-Q1 
   lower_bound = Q1 - 1.5 * IQR
   upper_bound = Q3 + 1.5 * IQR
   outliers = (data < lower_bound) | (data > upper_bound)
   return outliers, lower_bound, upper_bound

fig, axes = plt.subplots(4, 4, figsize=(18, 14))
fig.suptitle('Histogramy z outlierami (metoda IQR) - wszystkie cechy', 
             fontsize=16, fontweight='bold')

axes = axes.flatten()

for i, col in enumerate(df.columns):
    outliers, lower, upper = detect_outliers_iqr(df[col])
    
    axes[i].hist(df[col], bins=20, color='lightblue', edgecolor='black', alpha=0.7)
    axes[i].axvline(lower, color='red', linestyle='--', linewidth=1.5, alpha=0.7)
    axes[i].axvline(upper, color='red', linestyle='--', linewidth=1.5, alpha=0.7)
    
    # Zaznacz outliery
    if outliers.sum() > 0:
        axes[i].scatter(df[col][outliers], np.zeros(outliers.sum()), 
                       color='red', s=50, marker='x', zorder=5)
    
    axes[i].set_title(f'{col}\n({outliers.sum()} outlierów)', fontsize=9, fontweight='bold')
    axes[i].set_xlabel('Wartość', fontsize=7)
    axes[i].set_ylabel('Częstość', fontsize=7)
    axes[i].grid(True, alpha=0.3)

for i in range(len(df.columns), len(axes)):
    axes[i].axis('off')
plt.show()


In [ ]:
# TODO 5: Kategorie jakości
# - Low (<=5), Medium (5-6), High (>6)
# - porównanie cech
# - box plots

def categorize_quality(quality):
  if quality <= 5:
    return "Low"
  elif 5 < quality <= 6:
    return "Mid"
  else:
    return "High"


wine_df['quality_grade'] = wine_df['quality'].apply(categorize_quality)
print(wine_df.head())

### Wnioski

TODO: Napisz swoje wnioski:
Te zadania to raczej powtarzalne czynności, z którymi bardzo radzi sobie jakikolwiek LLM, ale mimo wszystko opanowanie operacji na DataFrame'ach daje duży boost produktywności. Według mnie właśnie takie niuanse jak bardzo dobra znajomość podstawowych bibliotek i narzędzi odróżnia dobrego inżyniera od bardzo dobrego.

---
## Podsumowanie

**Gratulacje!** ✓ Colab ✓ NumPy ✓ Pandas ✓ Matplotlib

**Następny:** Lab 1.2 - Preprocessing i pierwsze modele

**Kontakt:** lukasz.grala@cdv.pl